development:
  host: localhost
  database: iaato_development

test:
  host: localhost
  database: iaato_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOHQ_URL'] %>
